name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up docker
        uses: docker/setup-docker-action@v4
      - name: Build docker image (tag vai ser o hash do commit)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }} .
      - name: Execute suit tests jest 
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }} npm run test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image para o docker hub 
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }}
  cd:  
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1