name: CI 

on:
  pull_request:
    branches:
      - main

jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up docker
        uses: docker/setup-docker-action@v4
      - name: Build docker image (tag vai ser o hash do commit)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }} .
      - name: Execute suit tests jest 
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }} npm run test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image para o docker hub 
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }}
